version: "3.5"

services:
  onvif-rest-api:
    image: onvif-rest-api-go:latest
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - cam1=https://cam1.url/onvif/device_service
      - cam2=https://cam2.url/onvif/device_service
      - prod=https://prod.cam.url/onvif/device_service